"""baseline

Revision ID: 4e3bb0bb2d9f
Revises: 
Create Date: 2026-06-11 20:18:40.953883

"""
from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401 — autogenerate가 Vector 타입을 렌더링할 때 필요
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4e3bb0bb2d9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector 확장은 autogenerate가 잡지 못하므로 수동 추가 (새 DB 부트스트랩용)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktails',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('glass', sa.String(length=255), nullable=True),
    sa.Column('abv', sa.REAL(), nullable=True),
    sa.Column('num_like', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recipe', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_tag', sa.String(length=50), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_cocktails_base_tag', 'cocktails', ['base_tag'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('cocktail_ingredients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('cocktail_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cocktail_id', 'ingredient_id', name='cocktail_ingredients_cocktail_id_ingredient_id_key')
    )
    op.create_index('idx_cocktail_ingredients_cocktail', 'cocktail_ingredients', ['cocktail_id'], unique=False)
    op.create_index('idx_cocktail_ingredients_ingr', 'cocktail_ingredients', ['ingredient_id'], unique=False)
    op.create_table('likes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('cocktail_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cocktail_id', name='likes_user_id_cocktail_id_key')
    )
    op.create_index('idx_likes_cocktail', 'likes', ['cocktail_id'], unique=False)
    op.create_index('idx_likes_user', 'likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_likes_user', table_name='likes')
    op.drop_index('idx_likes_cocktail', table_name='likes')
    op.drop_table('likes')
    op.drop_index('idx_cocktail_ingredients_ingr', table_name='cocktail_ingredients')
    op.drop_index('idx_cocktail_ingredients_cocktail', table_name='cocktail_ingredients')
    op.drop_table('cocktail_ingredients')
    op.drop_table('users')
    op.drop_table('ingredients')
    op.drop_index('idx_cocktails_base_tag', table_name='cocktails')
    op.drop_table('cocktails')
    # ### end Alembic commands ###
