"""social login only: drop email auth, users social-only schema

Revision ID: 8695101089fe
Revises: a351ccf5bfa0
Create Date: 2026-07-08 00:45:46.957831

"""
from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401 — autogenerate가 Vector 타입을 렌더링할 때 필요
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8695101089fe'
down_revision: Union[str, None] = 'a351ccf5bfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_email_verifications_email'), table_name='email_verifications')
    op.drop_index(op.f('idx_email_verifications_request_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ⚠️ 전제조건: provider_id 가 NULL 인 기존 행(구 'local'/이메일 유저)이 없어야 NOT NULL 승격이 성공한다.
    #    상용 적용 전 `SELECT * FROM users WHERE provider_id IS NULL;` 로 확인하고, 있으면 정리할 것.
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('uq_users_provider_email'), 'users', type_='unique')
    op.drop_constraint(op.f('users_nickname_key'), 'users', type_='unique')
    op.drop_index(op.f('uq_users_provider_provider_id'), table_name='users', postgresql_where='(provider_id IS NOT NULL)')
    op.create_unique_constraint('uq_users_provider_provider_id', 'users', ['provider', 'provider_id'])
    # 'local' 개념 제거 → provider 기본값 없앰(신규 유저는 항상 provider 를 명시).
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=None)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'local'::character varying"))
    op.drop_constraint('uq_users_provider_provider_id', 'users', type_='unique')
    op.create_index(op.f('uq_users_provider_provider_id'), 'users', ['provider', 'provider_id'], unique=True, postgresql_where='(provider_id IS NOT NULL)')
    op.create_unique_constraint(op.f('users_nickname_key'), 'users', ['nickname'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_provider_email'), 'users', ['provider', 'email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('email_verifications',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('email_verifications_pkey')),
    sa.UniqueConstraint('request_id', name=op.f('email_verifications_request_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_email_verifications_request_id'), 'email_verifications', ['request_id'], unique=False)
    op.create_index(op.f('idx_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    # ### end Alembic commands ###
