"""add auth schema: users provider columns, email_verifications, refresh_tokens

Revision ID: a351ccf5bfa0
Revises: fa7a86e8e577
Create Date: 2026-07-05 17:03:02.029400

"""

from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401 — autogenerate가 Vector 타입을 렌더링할 때 필요
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a351ccf5bfa0"
down_revision: Union[str, None] = "fa7a86e8e577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verifications",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(
        "idx_email_verifications_email", "email_verifications", ["email"], unique=False
    )
    op.create_index(
        "idx_email_verifications_request_id",
        "email_verifications",
        ["request_id"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_refresh_tokens_token_hash", "refresh_tokens", ["token_hash"], unique=False
    )
    op.create_index(
        "idx_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "provider", sa.String(length=20), server_default="local", nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("provider_id", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_unique_constraint(
        "uq_users_provider_email", "users", ["provider", "email"]
    )
    op.create_index(
        "uq_users_provider_provider_id",
        "users",
        ["provider", "provider_id"],
        unique=True,
        postgresql_where="provider_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_users_provider_provider_id",
        table_name="users",
        postgresql_where="provider_id IS NOT NULL",
    )
    op.drop_constraint("uq_users_provider_email", "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "provider_id")
    op.drop_column("users", "provider")
    op.drop_index("idx_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("idx_refresh_tokens_token_hash", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "idx_email_verifications_request_id", table_name="email_verifications"
    )
    op.drop_index("idx_email_verifications_email", table_name="email_verifications")
    op.drop_table("email_verifications")
    # ### end Alembic commands ###
